name: Docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  APTOS_GIT_REVISION: aptos-node-v1.20.1

concurrency: docker

jobs:
  build_push:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: X64
            platform: linux/amd64
          - runner: ARM64
            platform: linux/arm64

    runs-on:
      - self-hosted
      - ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bake and populate builder-base and runtime-base cache
        if: github.event_name == 'push'
        uses: docker/bake-action@v5
        with:
          targets: cache-builder-base,cache-runtime-base
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Bake and populate binaries cache
        uses: docker/bake-action@v5
        with:
          targets: cache-binaries
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Bake images
        uses: docker/bake-action@v5
        with:
          targets: aptos-node,aptos
          push: ${{ github.event_name == 'push' }}
        env:
          PLATFORM: ${{ matrix.platform }}

  manifest:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        target: [aptos-node, aptos]

    needs: build_push
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Log into the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest
        run: |
          docker buildx imagetools create -t ghcr.io/shinamicorp/${{ matrix.target }}:${{ env.APTOS_GIT_REVISION }} \
            ghcr.io/shinamicorp/${{ matrix.target }}:${{ env.APTOS_GIT_REVISION }}-linux-amd64 \
            ghcr.io/shinamicorp/${{ matrix.target }}:${{ env.APTOS_GIT_REVISION }}-linux-arm64 \
