name: Docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  APTOS_GIT_REVISION: ee0d090   # devnet branch

concurrency: docker

jobs:
  build_push:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: X64
            platform: linux/amd64
          - runner: ARM64
            platform: linux/arm64

    runs-on:
      - self-hosted
      - ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log into the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Bake aptos
        uses: docker/bake-action@v4.1.0
        with:
          targets: aptos
          push: ${{ github.event_name == 'push' }}
          load: ${{ github.event_name != 'push' }}
        env:
          PLATFORM: ${{ matrix.platform }}

  manifest:
    strategy:
      fail-fast: false
      matrix:
        target: [aptos]

    needs: build_push
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Log into the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest
        run: |
          docker buildx imagetools create -t ghcr.io/shinamicorp/${{ matrix.target }}:${{ env.APTOS_GIT_REVISION }} \
            ghcr.io/shinamicorp/${{ matrix.target }}:${{ env.APTOS_GIT_REVISION }}-linux-amd64 \
            ghcr.io/shinamicorp/${{ matrix.target }}:${{ env.APTOS_GIT_REVISION }}-linux-arm64 \
